version: "3.5"

services:
  orderer3_mobileid_com:
    network_mode: mobileid-network
    command: orderer
    environment:
      FABRIC_LOGGING_SPEC: INFO
      ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
      ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/orderer.genesis.block
      ORDERER_GENERAL_GENESISMETHOD: file
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ENABLED: "true"
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
      ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR: "1"
      ORDERER_KAFKA_VERBOSE: "true"
      ORDERER_OPERATIONS_TLS_ENABLED: "false"
      ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:9446
      ORDERER_METRICS_PROVIDER: prometheus

      # Ledger configs and consensus parameters
      ORDERER_GENERAL_LEDGERTYPE: file
      ORDERER_FILELEDGER_LOCATION: /var/hyperledger/production/orderer
      ORDERER_FILELEDGER_PREFIX: hyperledger-fabric-ordererledger
      ORDERER_CONSENSUS_WALDIR: /var/hyperledger/production/orderer/etcdraft/wal
      ORDERER_CONSENSUS_SNAPDIR: /var/hyperledger/production/orderer/etcdraft/snapshot
    hostname: orderer3.mobileid.com
    container_name: orderer3.mobileid.com
    image: hyperledger/fabric-orderer:2.1.1
    # ports:
    #   - protocol: tcp
    #     published: 7050
    #     target: 7050
    volumes:
      - ../../../config/crypto-config/ordererOrganizations/mobileid.com/orderers/orderer3.mobileid.com/msp:/var/hyperledger/orderer/msp:rw
      - ../../../config/crypto-config/ordererOrganizations/mobileid.com/orderers/orderer3.mobileid.com/tls:/var/hyperledger/orderer/tls:rw
      - ../../../config/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block:rw
      # - ./orderer:/var/hyperledger/production/orderer:rw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    restart: always
